---
name: DevSecOps Pipeline
on:
  push:
    branches:
      - main

jobs:
  generate-version:
    name: Version Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      
      - name: get new version
        id: version
        run: |
          current_version="$(cat version)"
          new_version="$(echo "$current_version" | awk -F. '{$3 = $3 + 1;} 1' OFS=".")"
          echo "$new_version" > version
          echo "VERSION=$new_version" >> "$GITHUB_OUTPUT"

      - name: Build with Maven
        run: |
          mvn -B verify